import { KEYS } from "@/constants";
import { atom } from "recoil";

const defaultValue: HERITAGE[] = [
    {
        id: "1",
        name: "철제 은입사 화로",
        imageUrl: "/images/Heritage_1.svg",
        excavationLocation: "경상남도 밀양",
        era: "조선",
        category: "주생활 - 생활용품/가전 - 계절용 - 화로",
        size: "높이 15.8cm, 지름 15.2cm, 몸통지름 16.1cm",
        collectionNumber: "덕수 1485",
        currentLocation: "도쿄국립박물관",
        value: 100000000000,
        startDate: "1690873956088",
        expiredDate: "1696057956088",
    },
    {
        id: "2",
        name: "청자 상감 퇴화 풀꽃무늬 조롱박모양 주전자",
        imageUrl: "/images/Heritage_2.svg",
        excavationLocation: "경기도 - 개성부근",
        era: "고려",
        category: "",
        size: "",
        collectionNumber: "",
        currentLocation: "미국 매트로폴리탄 미술관",
        value: 100000000000,
        startDate: "",
        expiredDate: "",
    },
    {
        id: "3",
        name: "백자 청화 산수무늬 연적",
        imageUrl: "/images/Heritage_3.svg",
        excavationLocation: "경상남도 밀양",
        era: "조선",
        category: "",
        size: "",
        collectionNumber: "",
        currentLocation: "독일 쾰른 동아시아 미술관",
        value: 100000000000,
        startDate: "",
        expiredDate: "",
    },
    {
        id: "4",
        name: "바리모양 그릇 받침",
        imageUrl: "/images/Heritage_4.svg",
        excavationLocation: "경상남도 김해",
        era: "삼국시대",
        category: "",
        size: "",
        collectionNumber: "",
        currentLocation: "",
        value: 100000000000,
        startDate: "",
        expiredDate: "",
    },
    {
        id: "5",
        name: "국세 칙명지보",
        imageUrl: "/images/Heritage_5.svg",
        excavationLocation: "경기도 - 개성부근",
        era: "조선",
        category: "",
        size: "",
        collectionNumber: "",
        currentLocation: "도쿄국립박물관",
        value: 100000000000,
        startDate: "",
        expiredDate: "",
    },
];

export const heritageState = atom<HERITAGE[]>({
    key: KEYS.ATOM_HERITAGE,
    default: defaultValue,
});
